### ISSUE TITLE
第１２章の練習問題１番

### ISSUE THREAD

**Issue by TomoyukiAota** [taroyabuki/cppbook2#3]
第１２章の練習問題１番では、12-primes-thread4.cppを編集して解答を作成すると書かれてありますが、GitHub上の[12-primes-thread4.cpp](https://github.com/taroyabuki/cppbook2/blob/master/samples/12/12-primes-thread4.cpp)は既に解答になっています。
なお、12-primes-thread4.cppは、
* 本のp. 264に印刷されているコード
* GitHub上のコード

が異なります。本のp. 264に印刷されている12-primes-thread4.cppから解答を作成するのだとすると、つじつまが合います。

**Comment by taroyabuki** [comment]
ご指摘ありがとうございます。修正しました。
