### ISSUE TITLE
第６章の練習問題３番

### ISSUE THREAD

**Issue by TomoyukiAota** [taroyabuki/cppbook2#4]
本のp. 142の３番の箇所に印刷されたコードには、
```cout << endl;//出力値：5, 1, 4, 9, 2,```
と書かれていますが、正しくはGitHub上の[06-answer3.cpp](https://github.com/taroyabuki/cppbook2/blob/master/samples/answers/06/06-answer3.cpp)に書かれている
```cout << endl;//出力値：3, 5, 1, 4, 9, 2, ```
ではないでしょうか？

**Comment by taroyabuki** [comment]
ご指摘のとおりです。
Wikiに記載し，出版社に報告しました。
